import type { Product, Category } from './types'

const RAW_PREVIEW: any[] = [
  { 
    id: 'p1', 
    slug: 'top-lourdes',
    name: 'Top Lourdes',          
    base_price_uyu: 3450, 
    badge: 'Nuevo',
    status: 'active',
    category_id: 'tops',
    description: 'Tejido en algodón pima blanco con detalle floral. Edición a medida. Tiempo de tejido: 4–6 semanas.',
    created_at: new Date().toISOString(),
    sort_order: 1,
    lead_time_weeks_min: 4,
    lead_time_weeks_max: 6,
    material: 'Algodón Pima',
    care_instructions: 'Lavar a mano',
    is_custom_only: false,
    media: [{ id: 'm1', product_id: 'p1', url: '/photos/top-lace-parque.png', type: 'image', position: 0, is_primary: true, alt: null, created_at: '' }],
    category: { id: 'tops', name: 'Tops', slug: 'tops', sort_order: 1 } as Category,
    sizes: [
      { id: 's1', product_id: 'p1', size: 'S', price_uyu: null, available: true, sort_order: 1 },
      { id: 's2', product_id: 'p1', size: 'M', price_uyu: null, available: true, sort_order: 2 }
    ]
  },
  { 
    id: 'p2', 
    slug: 'bolero-petalo',
    name: 'Bolero Pétalo',         
    base_price_uyu: 4890, 
    badge: 'A medida',
    status: 'active',
    category_id: 'cardigans',
    description: 'Cropped bolero en hilo con sparkle, mangas anchas. Va sobre cualquier vestido para cambiar el día.',
    created_at: new Date().toISOString(),
    sort_order: 2,
    lead_time_weeks_min: 2,
    lead_time_weeks_max: 6,
    material: 'Hilo con lurex',
    care_instructions: '',
    is_custom_only: true,
    media: [{ id: 'm2', product_id: 'p2', url: '/photos/bolero-marron.png', type: 'image', position: 0, is_primary: true, alt: null, created_at: '' }],
    category: { id: 'cardigans', name: 'Cardigans', slug: 'cardigans', sort_order: 2 } as Category,
  },
  { 
    id: 'p3', 
    slug: 'top-blanco-sol',
    name: 'Top Blanco Sol',        
    base_price_uyu: 3890, 
    badge: 'Nuevo',
    status: 'active',
    category_id: 'tops',
    description: 'Top off-shoulder en algodón natural. Caída suave, tres cuartos de manga.',
    created_at: new Date().toISOString(),
    sort_order: 3,
    lead_time_weeks_min: 2,
    lead_time_weeks_max: 4,
    material: 'Algodón natural',
    care_instructions: '',
    is_custom_only: false,
    media: [{ id: 'm3', product_id: 'p3', url: '/photos/top-blanco.png', type: 'image', position: 0, is_primary: true, alt: null, created_at: '' }],
    category: { id: 'tops', name: 'Tops', slug: 'tops', sort_order: 1 } as Category,
    sizes: [{ id: 's3', product_id: 'p3', size: 'M', price_uyu: null, available: true, sort_order: 1 }]
  },
  { 
    id: 'p4', 
    slug: 'wrap-negro',
    name: 'Wrap Negro',            
    base_price_uyu: 5200, 
    badge: 'A medida',
    status: 'active',
    category_id: 'tops',
    description: 'Hombro descubierto en lana mohair negra. Una sola pieza, sin costuras laterales.',
    created_at: new Date().toISOString(),
    sort_order: 4,
    lead_time_weeks_min: 2,
    lead_time_weeks_max: 6,
    material: 'Lana Mohair',
    care_instructions: '',
    is_custom_only: true,
    media: [{ id: 'm4', product_id: 'p4', url: '/photos/wrap-negro.png', type: 'image', position: 0, is_primary: true, alt: null, created_at: '' }],
    category: { id: 'tops', name: 'Tops', slug: 'tops', sort_order: 1 } as Category,
  },
  { 
    id: 'p5', 
    slug: 'chaleco-avellana',
    name: 'Chaleco Avellana',      
    base_price_uyu: 5450, 
    badge: null,
    status: 'active',
    category_id: 'cardigans',
    description: 'Chaleco a botones con borde marrón profundo. Algodón natural sin teñir.',
    created_at: new Date().toISOString(),
    sort_order: 5,
    lead_time_weeks_min: 2,
    lead_time_weeks_max: 6,
    material: 'Algodón natural',
    care_instructions: '',
    is_custom_only: false,
    media: [{ id: 'm5', product_id: 'p5', url: '/photos/chaleco-marron.jpg', type: 'image', position: 0, is_primary: true, alt: null, created_at: '' }],
    category: { id: 'cardigans', name: 'Cardigans', slug: 'cardigans', sort_order: 2 } as Category,
    sizes: [{ id: 's5', product_id: 'p5', size: 'L', price_uyu: null, available: true, sort_order: 1 }]
  },
  { 
    id: 'p6', 
    slug: 'bufanda-verena',
    name: 'Bufanda Verena',        
    base_price_uyu: 1890, 
    badge: 'Nuevo',
    status: 'active',
    category_id: 'accesorios',
    description: 'Bufanda larga en verde musgo con rayas crema. 180 cm de largo.',
    created_at: new Date().toISOString(),
    sort_order: 6,
    lead_time_weeks_min: 2,
    lead_time_weeks_max: 3,
    material: '',
    care_instructions: '',
    is_custom_only: false,
    media: [{ id: 'm6', product_id: 'p6', url: '/photos/bufanda-verde.png', type: 'image', position: 0, is_primary: true, alt: null, created_at: '' }],
    category: { id: 'accesorios', name: 'Accesorios', slug: 'accesorios', sort_order: 3 } as Category,
  },
  { 
    id: 'p7', 
    slug: 'bufanda-frutilla',
    name: 'Bufanda Frutilla',      
    base_price_uyu: 1890, 
    badge: null,
    status: 'active',
    category_id: 'accesorios',
    description: 'Patchwork de rosa y rojo, terminación en franja. 165 cm.',
    created_at: new Date().toISOString(),
    sort_order: 7,
    lead_time_weeks_min: 2,
    lead_time_weeks_max: 3,
    material: '',
    care_instructions: '',
    is_custom_only: false,
    media: [{ id: 'm7', product_id: 'p7', url: '/photos/bufanda-rosa.jpg', type: 'image', position: 0, is_primary: true, alt: null, created_at: '' }],
    category: { id: 'accesorios', name: 'Accesorios', slug: 'accesorios', sort_order: 3 } as Category,
  },
  { 
    id: 'p8', 
    slug: 'bolso-manzana',
    name: 'Bolso Manzana',         
    base_price_uyu: 2450, 
    badge: null,
    status: 'active',
    category_id: 'accesorios',
    description: 'Bolso de hilo grueso, asa redonda. Disponible en rojo y negro.',
    created_at: new Date().toISOString(),
    sort_order: 8,
    lead_time_weeks_min: 2,
    lead_time_weeks_max: 3,
    material: '',
    care_instructions: '',
    is_custom_only: false,
    media: [{ id: 'm8', product_id: 'p8', url: '/photos/bolsos-rojo-negro.jpg', type: 'image', position: 0, is_primary: true, alt: null, created_at: '' }],
    category: { id: 'accesorios', name: 'Accesorios', slug: 'accesorios', sort_order: 3 } as Category,
  },
  { 
    id: 'p9', 
    slug: 'set-cobre',
    name: 'Set Cobre',             
    base_price_uyu: 7890, 
    badge: 'Edición limitada',
    status: 'active',
    category_id: 'sets',
    description: 'Top + falda en hilo cobre con lurex. Combinable o por separado.',
    created_at: new Date().toISOString(),
    sort_order: 9,
    lead_time_weeks_min: 3,
    lead_time_weeks_max: 5,
    material: 'Hilo Cobre',
    care_instructions: '',
    is_custom_only: false,
    media: [{ id: 'm9', product_id: 'p9', url: '/photos/set-marron.jpg', type: 'image', position: 0, is_primary: true, alt: null, created_at: '' }],
    category: { id: 'sets', name: 'Sets', slug: 'sets', sort_order: 4 } as Category,
    sizes: [
      { id: 's91', product_id: 'p9', size: 'S', price_uyu: null, available: true, sort_order: 1 },
      { id: 's92', product_id: 'p9', size: 'M', price_uyu: null, available: true, sort_order: 2 }
    ]
  },
]

export const DAHILA_PREVIEW_PRODUCTS: Product[] = RAW_PREVIEW.map(p => ({
  ...p,
  updated_at: p.created_at
}))
